# Generated by Django 4.1.7 on 2023-04-02 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Blogaaa', 'verbose_name_plural': 'Blogsbbb'},
        ),
    ]
