# Generated by Django 4.1.7 on 2023-04-02 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_delete_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Postsss', 'verbose_name_plural': 'Posts'},
        ),
    ]
