# Generated by Django 4.1.7 on 2023-04-02 04:14

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_category_post_author_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='django.png', upload_to=blog.models.user_directory_path),
        ),
    ]
